[package]
name = "reader-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
reader-app.workspace = true
reader-core.workspace = true
reader-integrations.workspace = true
reader-storage.workspace = true

ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
reader-formats.workspace = true
