[package]
name = "stealth-reader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
reader-app.workspace = true
reader-core.workspace = true
reader-formats.workspace = true
reader-storage.workspace = true
reader-tui.workspace = true

clap.workspace = true
sha2.workspace = true
